version: '3.8'

services:
  # Service 1: Your Frontend (React + Nginx)
  frontend:
    build: .
<<<<<<< HEAD
    ports:
      - "7500:80" # Expose on port 80
=======
    expose:
      - "80" # Expose on port 80
>>>>>>> bb887148676fd88679e6b4f5ce0fd35c64edd405
    depends_on:
      - backend

  # Service 2: Your Backend (Node Proxy)
  backend:
    build: ./server # Tells Docker to look in the /server folder
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
